@startuml
!include estilo.iuml
!pragma layout smetana

left to right direction
actor "Visitante" as V
actor "Usuario registrado" as U
actor "Administrador\nde BD" as A
actor "Analista de calidad\nde datos" as Q
actor "Desarrollador" as Dv
actor "Auditor interno" as Au
A -up-|> U
Q -up-|> U
Dv -up-|> U
Au -up-|> U
rectangle "Motor de Integridad Multibase NoSQL" {
  usecase "CU01 Registrar cuenta" as CU01
  usecase "CU02 Iniciar sesión" as CU02
  usecase "CU03 Cerrar sesión" as CU03
  usecase "CU04 Gestionar conexiones" as CU04
  usecase "CU05 Gestionar reglas\nde integridad" as CU05
  usecase "CU06 Validar registro\nprevio a la escritura" as CU06
  usecase "CU07 Ejecutar escaneo\npor lotes" as CU07
  usecase "CU08 Registrar violaciones" as CU08
  usecase "CU09 Monitorear motores" as CU09
  usecase "CU10 Consultar dashboard" as CU10
  usecase "CU11 Generar reporte\nde anomalías" as CU11
  usecase "CU12 Exportar reporte PDF" as CU12
  usecase "CU13 Ver usuarios en línea" as CU13
}
V --> CU01
V --> CU02
U --> CU03
U --> CU10
U --> CU13
A --> CU04
A --> CU07
A --> CU09
Q --> CU05
Q --> CU07
Q --> CU11
Dv --> CU06
Au --> CU11
CU07 ..> CU08 : <<include>>
CU12 ..> CU11 : <<extend>>
@enduml
